INSERT INTO interests (id, label) VALUES (DEFAULT, 'Autos & Vehicles');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Film & Animation');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Music');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Pets & Animals');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Sports');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Short Movies');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Travel & Events');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Gaming');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Videoblogging');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'People & Blogs');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Comedy');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Entertainment');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'News & Politics');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Howto & Style');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Education');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Science & Technology');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Nonprofits & Activism');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Movies');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Anime/Animation');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Action/Adventure');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Classics');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Dark Comedy');