INSERT INTO interests (id, label) VALUES (DEFAULT, 'Vegan Diets');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Technology Industry');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Fine Art Photography');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Cooking');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Music and Audio');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Dogs');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Summer Olympic Sports');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Makeup and Accessories');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Startups');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Information and Network Security');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Defense Industry');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'World Cuisines');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Auto Parts');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Fitness and Exercise');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Nutrition');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Drawing and Sketching');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Painting');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Photography');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Mental Health');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Environment');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Operating Systems');
INSERT INTO interests (id, label) VALUES (DEFAULT, 'Social Networking');