INSERT INTO users_interests (user_id, interest_id) VALUES (3, 5) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 22) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 15) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 17) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 15) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 2) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 22) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 8) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 13) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 17) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 22) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 3) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 20) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 2) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 6) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 3) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 14) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 10) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 1) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 3) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 19) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 3) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 6) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 3) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 10) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (5, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (5, 12) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 11) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 9) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 5) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 22) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 4) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (2, 15) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 6) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 21) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 13) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 20) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (5, 1) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (1, 19) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 4) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (5, 22) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (4, 19) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (3, 7) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (5, 1) ON CONFLICT(user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (6, 6) ON CONFLICT(user_id, interest_id) DO NOTHING;


INSERT INTO users_interests (user_id, interest_id) VALUES (7, 2) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 24) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 25) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 26) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 27) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 28) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 29) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 20) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 31) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 32) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (7, 33) ON CONFLICT (user_id, interest_id) DO NOTHING;

INSERT INTO users_interests (user_id, interest_id) VALUES (8, 2) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (8, 24) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (8, 25) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (8, 26) ON CONFLICT (user_id, interest_id) DO NOTHING;

INSERT INTO users_interests (user_id, interest_id) VALUES (9, 27) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (9, 28) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (9, 29) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (9, 20) ON CONFLICT (user_id, interest_id) DO NOTHING;

INSERT INTO users_interests (user_id, interest_id) VALUES (10, 31) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (10, 32) ON CONFLICT (user_id, interest_id) DO NOTHING;
INSERT INTO users_interests (user_id, interest_id) VALUES (10, 33) ON CONFLICT (user_id, interest_id) DO NOTHING;