INSERT INTO tags (id, label) VALUES (DEFAULT, 'electric skateboards');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'punk music');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'tik tok');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'dog memes');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'PvP');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'olympic hockey');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'cheap vegan food');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'salamanders');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'desert hiking');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'goth makeup');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'start-up businesses');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'ethical hacking');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'video art');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'trading crypto');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'tiny houses');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'bird photography');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'ece engineering');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'catan');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'cooking');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'how to write books');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'learning german');
INSERT INTO tags (id, label) VALUES (DEFAULT, 'fx trading');