INSERT INTO tags (id, label) VALUES (1, 'electric skateboards');
INSERT INTO tags (id, label) VALUES (2, 'punk music');
INSERT INTO tags (id, label) VALUES (3, 'tik tok');
INSERT INTO tags (id, label) VALUES (4, 'dog memes');
INSERT INTO tags (id, label) VALUES (5, 'PvP');
INSERT INTO tags (id, label) VALUES (6, 'olympic hockey');
INSERT INTO tags (id, label) VALUES (7, 'cheap vegan food');
INSERT INTO tags (id, label) VALUES (8, 'salamanders');
INSERT INTO tags (id, label) VALUES (9, 'desert hiking');
INSERT INTO tags (id, label) VALUES (10, 'goth makeup');
INSERT INTO tags (id, label) VALUES (11, 'start-up businesses');
INSERT INTO tags (id, label) VALUES (12, 'ethical hacking');
INSERT INTO tags (id, label) VALUES (13, 'video art');
INSERT INTO tags (id, label) VALUES (14, 'trading crypto');
INSERT INTO tags (id, label) VALUES (15, 'tiny houses');
INSERT INTO tags (id, label) VALUES (16, 'bird photography');
INSERT INTO tags (id, label) VALUES (17, 'ece engineering');
INSERT INTO tags (id, label) VALUES (18, 'catan');
INSERT INTO tags (id, label) VALUES (19, 'cooking');
INSERT INTO tags (id, label) VALUES (20, 'how to write books');
INSERT INTO tags (id, label) VALUES (21, 'learning german');
INSERT INTO tags (id, label) VALUES (22, 'fx trading');